version: '3.7'

services:
  consul-server-actor-microservices:
    image: hashicorp/consul:1.11.2
    container_name: consul-server
    restart: always
    volumes:
     - ./Consul/server.json:/consul/config/server.json:ro
     - ./Consul/certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
networks:
  consul:
    driver: bridge